[project]
name = "EpicCustomLoadBalancer"
version = "0.1.0"
description = "Custom Load Balancer for EPIC"
readme = "README.md"
requires-python = ">=3.12.11"
dependencies = [
    "fastapi[standard]>=0.115.14",
    "pydantic>=2.11.7",
]
